server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:~/Documents/cryptodatabase;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
#  security:
#    user:
#      name: user
#      password: senha

jwt:
  secret: F14P
  expiration: 3

fiap:
  debug: true
