spring:
  datasource:
#  docker run --name mysql-fiap -v /dev/mysql:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=password -d -p 3306:3306 mysql:8.0
    url: jdbc:mysql://localhost:3306/cryptodb
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always # never | embedded
      schema: classpath:schema.sql

file:
#  path: /Users/fabiomiyasato/Downloads/cryptobb/batch/file_to_delete.txt
  chunk: 3
  resource: crypto_import.csv
