spring:
  datasource:
    url: jdbc:h2:~/cryptodbbatch;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  batch:
    jdbc:
      initialize-schema: always

file:
  path: /Users/fabiomiyasato/Downloads/cryptobb/batch/file_to_delete.txt
